### ISSUE TITLE
Add support for CRDs

### ISSUE THREAD

**Issue by stan-sz** [Azure/bicep-types-k8s#49]
This is based on `aadpodidentity.k8s.io/v1` described at https://docs.microsoft.com/en-us/azure/machine-learning/how-to-use-azure-ad-identity which is homed in https://github.com/Azure/aad-pod-identity/tree/master/config/crd

**Comment by stan-sz** [comment]
aadpodidentity has been generated https://github.com/Azure/bicep-types-k8s/tree/main/generated/kubernetes/aadpodidentity.k8s.io/v1

**Comment by stan-sz** [comment]
Another example is `linkerd.io/ServiceProfile@v1alpha2` documented at https://linkerd.io/2.10/features/service-profiles/

**Comment by shenglol** [comment]
CRD support are added in Bicep v17.
